# step2: list, arrayを使ってみる

python には 複数の要素を扱う為の方法として，list [], tuple (), set, dictionary {}の概念があります．
list はC言語やfortrunで言う配列の上位概念に相当しますが，数値計算をする上でlistを配列として使うと計算速度が非常に遅くなります．
この問題を回避するためにnumpy にあるarrayを使うことが一般的だと思います．

ここではよく使うlist, numpy.arrayについて説明します． tuple, set, dictionaryも非常に便利な概念なのですが，ここでは触れません．

## list篇

list は 要素をひとつのグループにまとめたものでｂ

In [1]:
list1 = [7, 2.0 + 3.j, 1.0, "abc", lambda x: x**2 ]
print(list1)

[7, (2+3j), 1.0, 'abc', <function <lambda> at 0x7fc188074b70>]


リストの要素は

In [2]:
list1[0], list1[3]

(7, 'abc')

In [3]:
list1[-1], list1[-3]

(<function __main__.<lambda>>, 1.0)

のようにしてアクセスします．pythonはc言語と同じで配列のindexは0から始まります．
また-1は配列の末尾を意味し，-を付けることで後ろからアクセスすることができます．


リストの要素は異なる型を扱え，任意のオブジェクトを格納することができます．

In [4]:
for x in list1:
    print(type(x), x)

<class 'int'> 7
<class 'complex'> (2+3j)
<class 'float'> 1.0
<class 'str'> abc
<class 'function'> <function <lambda> at 0x7fc188074b70>


for分はc言語のfor文と異なります．itatable(list, tuple, numpy.array等々)の0番目の要素ををxに代入し，for文の末尾にまで行くと1番目の要素をxに代入・・・，と繰り返します．要素のindex番号も同時に欲しい場合は

In [5]:
for i, x in enumerate(list1):
    print(i, x)

0 7
1 (2+3j)
2 1.0
3 abc
4 <function <lambda> at 0x7fc188074b70>


とすると簡単です．要素の長さは

In [6]:
len(list1)

5

として調べることができます．listの要素を変更する場合は

In [7]:
list1[0] = 3
print(list1)

[3, (2+3j), 1.0, 'abc', <function <lambda> at 0x7fc188074b70>]


とします．複数の要素にアクセスする場合は

In [8]:
print(list1[2: ])
print(list1[2:-1])

[1.0, 'abc', <function <lambda> at 0x7fc188074b70>]
[1.0, 'abc']


とします．詳しくは list[start: end: every] となっており， startは 詳しくは次を参照

### listに対する演算

listに対する演算は整数の乗法，listの加法演算が定義されています．

In [9]:
x = [1] * 5
y = ["a"] * 3
print(x, y)

[1, 1, 1, 1, 1] ['a', 'a', 'a']


In [10]:
x = [1, 3, 4]
y = ["a", "b", "c"]
print(x + y)

[1, 3, 4, 'a', 'b', 'c']


が定義されています．

加法に似たmethodにappendが有りますが，違うものです．

In [11]:
x.append("d")
print(x)
x.append(["e", "f", "g"]) 
print(x)

[1, 3, 4, 'd']
[1, 3, 4, 'd', ['e', 'f', 'g']]


他にも，挿入，要素の取り出し等々が定義されています．ここを参照

## numpy array 篇．

数値計算を実行する上でlistを数値配列として用いる事も可能ですが，演算速度が非常に遅いという難点があります．
恐らく通常はnumpy.arrayを使う事が一般的だと思います(他の最適な方法は聞いたことが無いです)．

numpyのarrayを使うためにはnumpyをインストールする必要がありますが，anacondaを使用している場合はデフォルトでインストールされています．
実際に使ってみます．

In [12]:
import numpy as np
x = np.array([1, 2, 3])
print(x)

[1 2 3]


arrayはlistの様に任意のobjectを格納することができます．

In [13]:
y = np.array([1, "a", lambda x: x**2])
print(y)

[1 'a' <function <lambda> at 0x7fc188074ae8>]


### 四則演算
numpy arrayはlistとは異なる四則演算が定義されています．

In [14]:
a = np.array([1, 2, 3] ) + np.array([1, 2, 3])
b = np.array([1, 2, 3] ) - np.array([1, 2, 3])
c = np.array([1, 2, 3] ) * np.array([1, 2, 3])
d = np.array([1, 2, 3] ) / np.array([1, 2, 3])
print(a, b, c, d)

[2 4 6] [0 0 0] [1 4 9] [ 1.  1.  1.]


但し異なる長さのarrayや配列内に数値以外のobjectが有る場合はその限りではありません．

In [15]:
x = np.array([1, 2, 3]) 
x + np.array([1, 2, 3, 4])

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [16]:
x + np.array(["a", "b", "c"])

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

配列の要素へのアクセスは基本的にlistと同じです．

In [17]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x[1], x[-1])
print(x[2:-1:2])

2 10
[3 5 7 9]


numpyは配列を操作するための様々な操作が用意されています．詳しくはをご参照下さい．

### 多次元配列

numpy arrayは多次元配列オブジェクトです．

In [18]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


四則演算は各要素に対して定義されています．

次元数や，要素の型は

In [19]:
x.shape, x.dtype

((2, 3), dtype('int64'))

として調べる事ができます．要素に一つでも浮動小数点や複素数があると

In [20]:
x = np.array([1, 2, 3.0])
y = np.array([1, 2, 3.0 + 4.0j])
print(x.dtype, x)
print(y.dtype, y)

float64 [ 1.  2.  3.]
complex128 [ 1.+0.j  2.+0.j  3.+4.j]


要素の型は代入されたものから変更されます．

## 代入演算(=)に関する注意

代入演算はオブジェクトのコピーではなく，アドレスをコピーします．
何が言いたいかというとlist を = で代入すると

In [21]:
list1 = [1, 2, 'a']
list2 = list1
print(list1, list2)

[1, 2, 'a'] [1, 2, 'a']


と一見要素をコピーしているように見えますが

In [22]:
list1[0] = 3
print(list1, list2)

[3, 2, 'a'] [3, 2, 'a']


list1に対する操作の影響がlist2にも及んでいます．これは = の演算が要素をコビーするのではなく，list1がのメモリーアドレスがlist1に代入されているのだと思います．
配列の要素をコピーする場合は

In [23]:
list1 = [1, 2, 3]
list2 = list1.copy()
list1[0] = 4
print(list1, list2)

[4, 2, 3] [1, 2, 3]


のようにします．このことはnumpy arrayも同様で

In [24]:
x = np.array([1, 2, 3])
y = x
x[0] = 4
print(x, y)

[4 2 3] [4 2 3]


となります．numpyの場合

In [25]:
z = np.copy(x)
x[0] = 5
print(x, z)

[5 2 3] [4 2 3]


のようにします．

## listとarrayの演算速度の比較*

listを使うと計算速度が遅くなると言及しましたが具体的に比較してみます．
いい例ではありませんが，長さを$s$のlist or array 
\begin{equation}
x_i = \sum_{i=0}^{s} i
\end{equation}
を構成し $y = \sum_{i} x_i$を計算してみましょう．

具体的に$x_i$や$y$は次のようにして与えます．

In [26]:
x = [ ]
res = 0
for n in range(5):
    res+=n
    x.append(res)
    y = sum(x)
    print(n,x, y)

0 [0] 0
1 [0, 1] 1
2 [0, 1, 3] 4
3 [0, 1, 3, 6] 10
4 [0, 1, 3, 6, 10] 20


ここでrange(x,y,z)はxから y-1までz間隔のitarableなオブジェクトです．rangeは

In [27]:
range(5)

range(0, 5)

となります． range(5) = [0, 1, 2, 3, 4] と思っていただいて構いません．sumは代入された要素の和を意味します．さてlistの要素はs増大とともに長くなるので和だけを計算しましょう．

In [28]:
def sum_by_list(s):
    x = []
    res = 0.0 + 0.j
    for n in range(s):
        res += n + n*1.j
        x.append(res)
        y = sum(x)
    return y

演算時間を稼ぐため毎度和を取り，要素は複素数にしておきます．ます．同じことをnumpyで定義しましょう．

In [29]:
def sum_by_array(s):
    x = np.array([])
    res = 0 + 0.j
    for n in range(s):
        res += n + n*1.j
        x = np.append(x, res)
        y = np.sum(x)
    return y

次に演算速度を測るための関数を定義しましょう．

In [30]:
import time
def timing(func, x):
    a = time.time()
    res = func(x)
    b = time.time()
    return [b-a, res]

In [31]:
for s in [1000, 5000, 10000]:    
    a = timing(sum_by_list, s)
    b = timing(sum_by_array, s)
    print("list    : %.5f sec, res = %s" % (a[0],a[1]) )
    print("array: %.5f sec, res = %s" % (b[0], b[1]) )
    print()

list    : 0.02172 sec, res = (166666500+166666500j)
array: 0.01684 sec, res = (166666500+166666500j)

list    : 0.36702 sec, res = (20833332500+20833332500j)
array: 0.07445 sec, res = (20833332500+20833332500j)

list    : 1.43451 sec, res = (166666665000+166666665000j)
array: 0.20108 sec, res = (166666665000+166666665000j)



意図的に時間が掛かる実装にしましたが， 明らかにlistを使う方法は遅い事が分かります． なお，和の計算でnumpyのsumを使っていますが，
pythonのsumを使うとさらに遅くなります．このあたりの詳しいことは機会があればどこかでまとめましょう．

なにはともあれ数値演算に関してはnumpyで定義された関数を使うことが得策で，numpyを使いこなせるようになりましょう．